function h=SetupSlider()

    span = [0 1];

    h = figure('pos',[300 500 300 300],...
        'menubar','none',...
        'numbertitle','off',...
        'name',['Treshholds']);
    % Hue Max and min slider
        uicontrol(h,...
        'style','slider',...
        'pos',[10 260 280 20],...
        'min',span(1),...
        'max',span(2),...
        'value',span(2),...
        'callback',@sliderupdate,...
        'tag','hueTreshMax');
    
        uicontrol(h,...
        'style','slider',...
        'pos',[10 220 280 20],...
        'min',span(1),...
        'max',span(2),...
        'value',span(1),...
        'callback',@sliderupdate,...
        'tag','hueTreshMin');
    
    % Saturation Max and min slider
        uicontrol(h,...
        'style','slider',...
        'pos',[10 180 280 20],...
        'min',span(1),...
        'max',span(2),...
        'value',span(2),...
        'callback',@sliderupdate,...
        'tag','satTreshMax');
    
        uicontrol(h,...
        'style','slider',...
        'pos',[10 140 280 20],...
        'min',span(1),...
        'max',span(2),...
        'value',span(1),...
        'callback',@sliderupdate,...
        'tag','satTreshMin');
    
    % Value Max and min slider
        uicontrol(h,...
        'style','slider',...
        'pos',[10 100 280 20],...
        'min',span(1),...
        'max',span(2),...
        'value',span(2),...
        'callback',@sliderupdate,...
        'tag','valTreshMax');
    
        uicontrol(h,...
        'style','slider',...
        'pos',[10 60 280 20],...
        'min',span(1),...
        'max',span(2),...
        'value',span(1),...
        'callback',@sliderupdate,...
        'tag','valTreshMin');
    
    % Hue Max and Min text
         uicontrol(h,...
        'style','text',...
        'pos',[10 280 280 20],...
        'tag',['text_' 'hueTreshMax'],...
        'string',['hueTreshMax :' num2str(span(2))])
        uicontrol(h,...
        'style','text',...
        'pos',[10 240 280 20],...
        'tag',['text_' 'hueTreshMin'],...
        'string',['hueTreshMin :' num2str(span(1))])
    
    % Saturation Max and Min text
         uicontrol(h,...
        'style','text',...
        'pos',[10 200 280 20],...
        'tag',['text_' 'satTreshMax'],...
        'string',['satTreshMax :' num2str(span(2))])
        uicontrol(h,...
        'style','text',...
        'pos',[10 160 280 20],...
        'tag',['text_' 'satTreshMin'],...
        'string',['satTreshMin :' num2str(span(1))])
    
    % Value Max and Min text
         uicontrol(h,...
        'style','text',...
        'pos',[10 120 280 20],...
        'tag',['text_' 'valTreshMax'],...
        'string',['valTreshMax :' num2str(span(2))])
        uicontrol(h,...
        'style','text',...
        'pos',[10 80 280 20],...
        'tag',['text_' 'valTreshMin'],...
        'string',['valTreshMin :' num2str(span(1))])
    
    
    % Log button
        uicontrol(h, ...
        'Style', 'pushbutton', ...
        'String', 'Log',...
        'Position', [20 20 50 20],...
        'Callback', @Logging);       
    

end

% -------------------
